### ISSUE TITLE
Derived instances for Rational are wrong

### ISSUE THREAD

**Issue by natefaubion** [anttih/purescript-rationals#13]
This commit https://github.com/anttih/purescript-rationals/commit/b101713c1272726024bb5c7a826cfc8217134326 replaced the instances with derived instances, but they are not the same. The previous implementation always reduced the rational. Can we revert this change?

**Comment by anttih** [comment]
Ooops 🙈.

**Comment by anttih** [comment]
Made a 2.1.0. Thanks!
