### ISSUE TITLE
Ring (Ratio a) instance is unlawful

### ISSUE THREAD

**Issue by hdgarrood** [anttih/purescript-rationals#28]
For example, consider the ring ℤ/4ℤ, i.e. the ring of integers modulo 4 (see [purescript-modular-arithmetic](https://pursuit.purescript.org/packages/purescript-modular-arithmetic/2.0.0) for more details). This ring has 2 as a zero divisor, i.e. in ℤ/4ℤ, we have that 2*2=0.

If we first define `mkZ4 x = mkZ x :: Z D4` (note: the `Z` type is from modular-arithmetic, and this function `mkZ4` turns a regular `Int` into an element of ℤ/4ℤ), then we have:

```purescript
> x = Ratio (mkZ4 1) (mkZ4 2)
> y = x + x
> numerator y
0
> denominator y
0
> z = y - x
> numerator z
0
> denominator z
0
```

Adding `x` to `x` and then subtracting `x` again should yield `x`, but we get 0/0.

In general, according to the [Field of fractions Wikipedia page](https://en.wikipedia.org/wiki/Field_of_fractions), we need to have an integral domain to be able to make a field of fractions; importantly, part of the definition of an integral domain is that it has no zero divisors, and it's the fact that we have a zero divisor as our denominator that is the source of the problem here.

As for addressing this, we don't have a type class for integral domains in the Prelude, but we do have `EuclideanRing`, which is a little stronger.

I also noticed that `Ratio` doesn't do any reduction after arithmetic operations, which perhaps limits its utility on its own. So I'm sort of wondering whether `Ratio` can justify its existence as a separate type at this point; if you need to wrap it in a newtype and provide separate instances to make it useful and lawful, why not just define `Rational` as `data Rational = Rational Int Int` in the first place?

I see two ways forward:

1. Try to make `Ratio` useful in its own right - in particular this would involve strengthening to a `EuclideanRing a` constraint on the numeric instances, and working out how to generalise reduction so that it can work on types other than just `Int`; this might involve implementing it in terms of an arbitrary `EuclideanRing` or something else.
2. Decide that ratios of more exotic types than `Int` is out of scope for this library (in which case it might be worth considering getting rid of the `Ratio` type entirely and just providing `Rational`).

If we implemented reduction in terms of an arbitrary `EuclideanRing` we could have

```purescript
reduce :: forall a. Eq a => EuclideanRing a => a -> a -> Ratio a
reduce n d =
  let
    x = Prelude.gcd n d
  in
    Ratio (n / x) (d / x)
```

although this has the slight drawback that we lose a bit of control; in the case of `Ratio Int`, for negative rationals, we would have the denominator being negative rather than the current behaviour which makes the numerator negative. I also haven't yet been able to verify whether the above implementation will always choose the same representative for a given ratio, i.e. there might be some instances where two ratios which are "the same" come out differently. Another approach might be to put the `reduce` function into a type class so that each type `a` can provide its own reduction.

Thoughts?

**Comment by anttih** [comment]
The idea of `Ratio` was to later implement a `BigRational` (`Ratio BigInt`) on top of it and also to be able to implement more "exotic" ratios as mentioned by @paf31 [here](https://github.com/anttih/purescript-rationals/issues/3). I didn't yet implement `BigRational` and I'm not sure how much people are using `Ratio`. I'm not using `Ratio` at the moment, at least.

With this in mind I'd try to aim for 1). If you can find a way to make the `EuclideanRing` thing work so that you are satisfied with it I'd be happy to accept a PR. I'd be happy to hear others' comments as well on this.

**Comment by hdgarrood** [comment]
Ok great :) I'll have a think and see what I can come up with.

**Comment by hdgarrood** [comment]
So I think the problem stems from the `numerator` and `denominator` functions. In the field of fractions of some integral domain, the elements are really equivalence classes of pairs rather than the pairs themselves (please let me know if I've lost you). With that in mind, being able to ask for "the" numerator is a bit of an issue, because 1/2 and 2/4 are the same fraction, but of course asking for the numerator of each would give you a different answer.

As I mentioned before one option would be to come up with a way of getting a canonical representative for each element of this field so that the `numerator` function can be made safe. I expect (but haven't been able to verify) that this would require adding a new type class, which would probably be along the lines of `class Reducible a where reduce :: a -> a -> Tuple a a`.

The other option, which has just occurred to me, is that we actually remove `numerator` and `denominator` from `Ratio`, and instead provide something like `embed :: forall a b. EuclideanRing b => (a -> b) -> Ratio a -> b` which allows you to convert a `Ratio` into an element of some other `EuclideanRing` by applying the supplied function to the numerator and denominator, and then dividing the results, i.e. `embed f (Ration n d) = f n / f d`. So e.g. Rational's `toNumber` could be implemented as `embed Data.Int.toNumber`, or you could get the approximate value of a fraction by just doing `embed id`.

**Comment by hdgarrood** [comment]
Although in the case of `embed`, to make that safe, I think the function needs to be a ring homomorphism. Maybe it would be better to keep `numerator` and `denominator` but add a note that some care should be taken.

**Comment by anttih** [comment]
What if we removed the `Rational` newtype entirely and made `Ratio` always reduce? This does not solve the zero division problem but at least now a `Ratio` is always reduced using `EuclideanRing`.

This is what the [haskell implementation](https://hackage.haskell.org/package/base-4.9.1.0/docs/src/GHC.Real.html#%25) does but using `Integral`.

I made an implementation of this [here](https://github.com/anttih/purescript-rationals/commit/ecdd9f5942aa5549e0fcd96d8d8260e1ce98bfd9) but for some reason the Ord Antisymmetry law is failing 🤔 

I also had to remove the `Field` instance since `Int` is not a `Field`.

**Comment by hdgarrood** [comment]
With that implementation we still need an `Ord` constraint, which would rule out a few instances, like polynomials and Gaussian integers (ie complex numbers with integral real and imaginary parts).

The zero division problem is actually solved by having a `EuclideanRing a` constraint on the `Semiring (Ratio a)` instance, because the `EuclideanRing` laws ensure that the product of two nonzero elements is nonzero.

Also `Ratio a` should have a `Field` instance, but it should only require a `EuclideanRing a` constraint.

Regarding that `Ord` instance, I think the problem is that everything flips around if `y` is negative; imagine x=1, y=-1. I think they need to be subtracted rather than divided. How about:

```
  compare x y =
    case x - y of
      Ratio n d ->
        if n == zero
          then EQ
          else case n > 0, d > 0 of
            true, true -> GT
            false, false -> GT
            _, _ -> LT
```

**Comment by hdgarrood** [comment]
Oops, that should be `zero` instead of the literal `0` there.

**Comment by anttih** [comment]
Indeed, that was the reason the Ord instance didn't work. Thanks! Also added back the `Field` instance.

What do you think about this implementation? I quite like it. It makes `Ratio` useful and we lose nothing regarding `Rational`. Any other `Ratio x` will also have the same API, mainly the `(%)` operator. The API is also a bit simpler now, you don't have to `runRational` to get to the numerator and  denominator.

As for the exclusion of some useful instances you mentioned, do you think we could live without those? I think this API solves all the use-cases we have had so far and even makes it better for some like `BigInt` so I'd err on the side of accepting this.

**Comment by anttih** [comment]
Now as a PR #29

**Comment by hdgarrood** [comment]
I'm not using those instances I mentioned, and I imagine they're very uncommon to see in actual code, so I don't think it's much of a problem to lose them. I agree, this looks like a big improvement :+1:
