### ISSUE TITLE
Question: why not generalize over Semiring?

### ISSUE THREAD

**Issue by paf31** [anttih/purescript-rationals#3]
Pretty much everything you have would work if you replaced `Int` with an arbitrary `Semiring`.

Would you be interested in that approach at all?

_Edit_: e.g. you could use "rationals" constructed from polynomial rings.

**Comment by anttih** [comment]
I don't see why not. Maybe we should add a more general `Ratio`?

```
data Ratio a = Ratio a a
type Rational = Ratio Int
```
