### ISSUE TITLE
PureScript 0.14

### ISSUE THREAD

**Issue by newlandsvalley** [anttih/purescript-rationals#34]
I've been looking at upgrading this to PS 0.14.  So far I've added spago and replaced StrongCheck with QuickCheck.  All is fine except for the fact that now, the SemiRing distribution test crashes.  I've no idea why or how to fix it at the moment.

Would you like a PR with what I've got or would you prefer to look at it yourself?

**Comment by anttih** [comment]
Please go ahead and PR it, we can try to look at it together.

**Comment by newlandsvalley** [comment]
Thanks - submitted!

**Comment by newlandsvalley** [comment]
The semiring left distribution test seems to work for integers in the range -200 to +200.  Beyond that, the failures are showing pretty big numbers - for example:

```
Error: Test 4 (seed 2079900095) failed: 
-37665 % 583219 /= 184596165 % 1436610977
````
when tested with 

```
semiringLeftDistribution :: TestRational -> TestRational -> TestRational -> Result
semiringLeftDistribution (TestRational a) (TestRational b) (TestRational c) = 
      a * (b + c) === (a * b) + (a * c)
```

**Comment by newlandsvalley** [comment]
Just to log a bit more information with another seed: 

```
Error: Test 1 (seed 1200765269) failed: 
-8982137 % 4155624 /= 1627272607 % 1234220328
```

where: 

```
a is -283 % 297 b is 245 % 88 c is -82 % 159
```

The LHS seems about right but I think the RHS has overflowed.

**Comment by newlandsvalley** [comment]
As far as I can see, purescript's ```ints``` are restricted to 32-bit integers.  See, for example the [Data.Int.53 documentation](https://pursuit.purescript.org/packages/purescript-int-53/4.0.0/docs/Data.Int53). In the worst-case scenario for the test, we might have denominators respectively of 997, 998 and 999, in which case the intermediate result would use an integer of 10 to the power 12 - well beyond this range.  If so, I can't see how the strongcheck  test would have passed.

**Comment by anttih** [comment]
Yeah this is a known issue. See #33 for example.

**Comment by newlandsvalley** [comment]
Ah, I stupidly hadn't looked at that.
