### ISSUE TITLE
I think you should be able to publish a release now.

### ISSUE THREAD

**Issue by newlandsvalley** [anttih/purescript-rationals#37]
We finally got to the bottom of the problem with bigints.  Version 5.0.0 was still using the PureScript 0.13 libraries.  See https://github.com/sharkdp/purescript-bigints/issues/36.

**Comment by newlandsvalley** [comment]
Not sure how you want to take it forward, but I've issued a PR against the `fix/travis-spago` branch which uses the ps 0.14 compatible version of `bigints` plus a handful of smaller updates to dependencies.

**Comment by gbagan** [comment]
Could you publish a new release after accepting my PR
https://github.com/anttih/purescript-rationals/pull/39
The bower.json of the last released version refers to packages with purescript version 0.13.

**Comment by newlandsvalley** [comment]
I have just now attempted to publish ```abc-parser``` using the new ```Registry```.  It failed because it could not resolve dependencies in order to build the manifest,  This could be resolved if you could publish a version that is PS 0.15 compatible (as it currently is).

**Comment by newlandsvalley** [comment]
Now done - many thanks.
