### ISSUE TITLE
trig functions?

### ISSUE THREAD

**Issue by hdgarrood** [anttih/purescript-rationals#9]
Now I realise this might be a bit against the ideas of this library, given that it would have to be approximate, since the real trig functions are defined on irrationals (such as pi) too. But.

It would be super useful to have `sin, cos :: Rational -> Rational`. I think they can be implemented using power series. It might be worth investigating how real maths libraries would do it.

In fact, doing it as a power series could be awesome, because then we might be able to define `sin :: (Num a) => a -> a`, and we could then use that same function on complex numbers such as in purescript-complex too. (Although if so, it might be out of scope for this library).

At the moment, your only option for trigonometry in PureScript is using `Number`, which is, well, meh.

**Comment by Thimoteus** [comment]
Hmmm. I have a [Taylor expansion](https://github.com/Thimoteus/purescript-symbolic-differentiation/blob/master/docs/Math/Differentiable/Real.md#taylorexpansion) function in my symbolic differentiation lib. Right now it only uses "real"-valued functions, but it should be possible to do the same for rationals.

**Comment by hdgarrood** [comment]
I think I'll close this as there's not much interest, I don't have a real use case in mind for it, and it can be done with any `Field` using power series.
